name: notes
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.0.18
  flutter_bloc: ^8.1.2
  bloc: ^8.1.1
  get_it: ^7.2.0
  cupertino_icons: ^1.0.2
  sqflite: ^2.2.6
  font_awesome_flutter: ^10.4.0
  image_picker: ^0.8.7+1
  permission_handler: ^10.2.0
  camera: ^0.10.3+2
  path_provider: ^2.0.14
  path: ^1.8.2
  flutter_launcher_icons: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_icons:
  android: true
  image_path: "assets/images/notes.png"
  min_sdk_android: 21
flutter:

  uses-material-design: true

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
